import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import RestaurantStyle from "@/styles/Restaurant.module.scss"
import { useEffect, useState } from 'react'
import { useSelector } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const test = useSelector((state)=>{console.log(state)})
  const [Restaurant, setRestaurant] = useState([
    {
      id:1,
      name:"전셰프의 뷔페플러스1",
      imageUrl:"https://i.postimg.cc/LXK1QHQV/f-Po-Z31584321311.jpg",
      recommand:5,
      type:"korean",
      comment:[
        {"id":1, "name":"테스트맨", "comment":"좋아요 전셰프의 뷔페플러스1 전셰프의 뷔페플러스1  전셰프의 뷔페플러스1 전셰프의 뷔페플러스1  전셰프의 뷔페플러스1 전셰프의 뷔페플러스1  전셰프의 뷔페플러스1 전셰프의 뷔페플러스1 "},
        {"id":1, "name":"테스트맨", "comment":"좋아요 전셰프의 뷔페플러스1 전셰프의 뷔페플러스1  전셰프의 뷔페플러스1 전셰프의 뷔페플러스1  전셰프의 뷔페플러스1 전셰프의 뷔페플러스1  전셰프의 뷔페플러스1 전셰프의 뷔페플러스1 "}
      ]
    },
    {
      id:2,
      name:"전셰프의 뷔페플러스1",
      imageUrl:"https://i.postimg.cc/LXK1QHQV/f-Po-Z31584321311.jpg",
      recommand:5,
      type:"korean",
      comment:[
        {"id":1, "name":"테스트맨", "comment":"좋아요 전셰프의 뷔페플러스1 전셰프의 뷔페플러스1  전셰프의 뷔페플러스1 전셰프의 뷔페플러스1  전셰프의 뷔페플러스1 전셰프의 뷔페플러스1  전셰프의 뷔페플러스1 전셰프의 뷔페플러스1 "}]
    },
  ])
  useEffect(()=>{
    console.log("TEST");
  },[]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={RestaurantStyle.Wrapper}>
          {
            Restaurant.map(({id,name,imageUrl,recommand,comment},idx) => (<ul key={idx}>
              <li>{name}</li>
              <li><img src={imageUrl}/></li>
              <li>{recommand}</li>
              <li>
                <ul>
                  {
                    comment.map(({name,comment},idx)=>(
                      <li key={idx}>
                        <ul>
                          <li>
                            {name}
                          </li>
                          <li>
                            {comment}
                          </li>
                        </ul>
                      </li>
                    ))
                  }
                  <li>
                    <ul>
                      <li>
                        <input type="text" placeholder='작성자'/>
                      </li>
                      <li>
                        <textarea placeholder='내용을 입력하시오'/>
                        <button>댓글 쓰기</button>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>
            </ul>))
          }
        </div>        
      </main>
    </>
  )
}
